### ISSUE TITLE
Method clean_up_df should only convert numeric types to str

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#313]
The `clean_up_df` method currently tries to convert every value in a DataFrame to a string. It should only do this for numeric types, not lists or dicts. This comes into play when trying to load data:

```
2019-05-23 10:10:39,990 - DataIngestPipeline - ERROR - {"_status":{"code":400,"message":"could not create genomic_file: {'hashes': ['Not a valid mapping type.'], 'urls': ['Not a valid list.']}}

2019-05-23 10:10:39,989 - LoadStage - DEBUG - Request body:
{'availability': 'Immediate Download',
 'data_type': 'Aligned Reads',
 'external_id': 's3://kf-seq-data-bcm/chung/HKT73CCXX-5.hgv.bam',
 'file_format': 'bam',
 'file_name': 'HKT73CCXX-5.hgv.bam',
 'hashes': "{'md5': '98ebe560095b231a3050812cc58a8b84-8100'}",
 'is_harmonized': 'False',
 'reference_genome': 'hs37d5',
 'sequencing_experiment_id': None,
 'size': '67939600949',
 'urls': "['s3://kf-seq-data-bcm/chung/HKT73CCXX-5.hgv.bam']"}
```
The field `hashes` should be a dict and field `urls` should be a list since that's what these fields were mapped to in the extract configs. However, because `clean_up_df` applies `numeric_to_str` to every value in the data, these types are lost.

A check should be added to `clean_up_df` to apply `numeric_to_str` to values are are not of type `list` or `dict`.

Additionally, changes must be made to stage's `_post_concept_discovery` since now the DataFrame data may have strings, lists, and dicts and the current implementation will error.

**Comment by fiendish** [comment]
'98ebe560095b231a3050812cc58a8b84-8100' is not a valid md5

**Comment by fiendish** [comment]
🤔

What if the loader just runs ast.literal_eval on the values to check for dicts or a lists?

**Comment by fiendish** [comment]
This specific issue also goes away when https://github.com/kids-first/kf-api-dataservice/issues/487 is fixed

**Comment by znatty22** [comment]
> This specific issue also goes away when kids-first/kf-api-dataservice#487 is fixed

This is true, but converting every value to a string still isn't the right thing to do. 

Now I'm even wondering whether we should be converting numeric types to strings in `clean_up_df`. I don't like that my source data has one set of types but then the data that my extract config operations are operating on has a different set of types. 

For example my source data has an `AFFECTED_STATUS` column with ints and there are two possible values: 1 or 2. Now when I write a `value_map` operation for this column, I have to know that the values in this column got converted to strings. So then my map will be 
```
m={
    '1': True,
    '2': False
}
``` 
instead of 
```
m={
    1: True,
    2: False
}
``` 
which is confusing and unexpected until you understand that `clean_up_df` is being called before operations are applied (and after). 

Maybe the user should be more in charge of how their values are converted. And `clean_up_df` can do the nan replacement only? The user can decide which columns to do a `numeric_to_str` conversion by calling this method in their mapping function for a `value_map` operation.

**Comment by fiendish** [comment]
> I don't like that my source data has one set of types

This is a false understanding of the source data. Your source data does _not_ have any types. Types are only ever _inferred_.

**Comment by znatty22** [comment]
Technically all true but then why doesn't pandas or any other similar library just convert everything to strings and leave the user to convert into desired types? Its because pandas is trying to infer the type of a column based on the values of that column. 

I guess its ok if we want to eliminate this inference. It just means that when I want to explore my data using pandas or something else in a Jupyter Notebook, now I have to remember to call clean_up_df on my dataframe before exploring it

**Comment by fiendish** [comment]
> then why doesn't pandas or any other similar library just convert everything to strings and leave the user to convert into desired types

Because pandas has bad defaults.

You can tell pandas to load your file without the conversions by telling it to load with dtype object or string.

**Comment by znatty22** [comment]
> then runs ast.literal_eval on values that start with { or [ 

I think this is a good short term solution. And then in the near future we should talk about redesigning both concept schema and target API config schema to include types (and other improvements).

>  What if the loader checks the first character 

I think this should happen in transform stage since its about transformation. We could rename `handle_nulls` to something else and do that check above this line https://github.com/kids-first/kf-lib-data-ingest/blob/daf0a280dd43c46a8da6368355cf3e5de65d2883/kf_lib_data_ingest/etl/transform/transform.py#L244?

**Comment by fiendish** [comment]
I guess, but that section is under a comment that says " # Convert nulls". It's not exactly null-related.

**Comment by fiendish** [comment]
Though that function maybe should be rewritten anyway. Why are there _any_ Nones left in the output?
